-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 11:04:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema vending_machine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vending_machine` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `vending_machine`;

-- -----------------------------------------------------
-- Table `vending_machine`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vending_machine`.`location` (
    `location_id` INT NOT NULL AUTO_INCREMENT,
    `school` VARCHAR(45) NOT NULL,
    `block` INT NOT NULL,
    `floor` INT NOT NULL,
    PRIMARY KEY (`location_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `vending_machine`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vending_machine`.`status` (
    `status_id` INT NOT NULL AUTO_INCREMENT,
    `status_name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`status_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `vending_machine`.`vending_machine`
-- ----------------------------------------------------- 
CREATE TABLE IF NOT EXISTS `vending_machine`.`vending_machine` (
    `vending_machine_id` INT NOT NULL AUTO_INCREMENT,
    `location_id` INT NULL,
    `vendor_name` VARCHAR(255) NULL,
    `status_id` INT NULL,
    PRIMARY KEY (`vending_machine_id`),
    INDEX `location_id_idx` (`location_id` ASC) VISIBLE,
    INDEX `status_id_idx` (`status_id` ASC) VISIBLE,
    CONSTRAINT `location_id` FOREIGN KEY (`location_id`) REFERENCES `vending_machine`.`location` (`location_id`) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT `status_id` FOREIGN KEY (`status_id`) REFERENCES `vending_machine`.`status` (`status_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `vending_machine`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vending_machine`.`payment_method` (
    `payment_id` INT NOT NULL AUTO_INCREMENT,
    `payment_name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`payment_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `vending_machine`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vending_machine`.`item` (
    `item_id` INT NOT NULL AUTO_INCREMENT,
    `item_name` VARCHAR(100) NULL,
    `item_cost` DECIMAL(5, 2) NOT NULL,
    `item_image` VARCHAR(255) NOT NULL,
    `availability` TINYINT NULL,
    PRIMARY KEY (`item_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `vending_machine`.`vending_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vending_machine`.`vending_payment` (
    `vending_payment_id` INT NOT NULL AUTO_INCREMENT,
    `vending_id` INT NULL,
    `payment_id` INT NULL,
    PRIMARY KEY (`vending_payment_id`),
    INDEX `vending_id_idx` (`vending_id` ASC) VISIBLE,
    INDEX `payment_id_idx` (`payment_id` ASC) VISIBLE,
    CONSTRAINT `vending_id` FOREIGN KEY (`vending_id`) REFERENCES `vending_machine`.`vending_machine` (`vending_machine_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `payment_id` FOREIGN KEY (`payment_id`) REFERENCES `vending_machine`.`payment_method` (`payment_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `vending_machine`.`vending_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vending_machine`.`vending_item` (
    `vending_item_id` INT NOT NULL AUTO_INCREMENT,
    `vending_machine_id` INT NULL,
    `item_id` INT NULL,
    `quantity` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`vending_item_id`),
    INDEX `vending_machine_id_idx` (`vending_machine_id` ASC) VISIBLE,
    INDEX `item_id_idx` (`item_id` ASC) VISIBLE,
    CONSTRAINT `vending_machine_id` FOREIGN KEY (`vending_machine_id`) REFERENCES `vending_machine`.`vending_machine` (`vending_machine_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `item_id` FOREIGN KEY (`item_id`) REFERENCES `vending_machine`.`item` (`item_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

/*SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE vending_machine;
TRUNCATE TABLE item;
TRUNCATE TABLE vending_item;
TRUNCATE TABLE location;
TRUNCATE TABLE payment_method;
TRUNCATE TABLE status;
TRUNCATE TABLE vending_item;
TRUNCATE TABLE vending_payment;

SET FOREIGN_KEY_CHECKS = 1;*/

INSERT INTO
    `vending_machine`.`location` (`school`, `block`, `floor`)
VALUES ('Design School', 1, 1),
    (' Engineering School', 2, 3),
    ('IT School', 3, 2),
    ('Business School', 4, 4),
    (
        ' Applied Science School',
        5,
        1
    );

INSERT INTO
    `vending_machine`.`status` (`status_name`)
VALUES ('Active'),
    ('Inactive'),
    ('Under Maintenance'),
    ('Out of Service');

INSERT INTO
  `vending_machine`.`payment_method` (`payment_name`) 
VALUES('Cash'),('PayNow'),('EZ-Link'),('NETS');

INSERT INTO
    `vending_machine`.`item` (
        `item_name`,
        `item_cost`,
        `item_image`,
        `availability`
    )
VALUES (
        'Coca-Cola Can',
        1.80,
        '/item_images/Coca-Cola Original.webp',
        1
    ),
    (
        'Fanta Orange',
        2.00,
        '/item_images/Fanta Orange.webp',
        1
    ),
    (
        'Heaven and Earth',
        1.50,
        '/item_images/Heaven and Earth Jasmine Green Tea.webp',
        1
    ),
    (
        'Nescafe',
        2.50,
        '/item_images/Nescafe Original.webp',
        1
    ),
    (
        'Red Bull Can',
        3.00,
        '/item_images/Red Bull Original.webp',
        1
    ),
    (
        'Ice mountain',
        1.00,
        '/item_images/Ice Mountain Mineral Water.webp',
        1
    ),
    (
        'Milo',
        3.00,
        '/item_images/Milo Original.webp',
        1
    ),
    (
        '100 plus',
        2.00,
        '/item_images/100 Plus Original.webp',
        0
    ),
    (
        'Pringle og',
        3.00,
        '/item_images/Pringles Original.webp',
        1

    ),
    (
       '7UP Lemon Lime',
       1.20,
       '/item_images/7UP Lemon Lime.webp',
       1

    );
    

INSERT into
    `vending_machine`.`vending_machine` (
        `location_id`,
        `vendor_name`,
        `status_id`
    )
VALUES (1, 'Royal Vending Pte Ltd', 1),
    (2, 'Le Tach Vending Pte Ltd', 1),
    (3, 'Atlas Vending Solutions Pte Ltd', 2),
    (4, 'Warburg Vending', 3),
    (5, 'Premier Vending Pte Ltd', 1);

select * from item;

INSERT INTO
    `vending_machine`.`vending_payment` (`vending_id`, `payment_id`)
VALUES (1, 1),
    (1, 2),
    (1, 3), 
    (2, 3), 
    (2, 4), 
    (3, 1), 
    (3, 2), 
    (3, 4), 
    (4, 1),
    (4, 2),
    (5, 2), 
    (5, 3),
    (5, 4);

INSERT INTO
    `vending_machine`.`vending_item` (
        `vending_machine_id`,
        `item_id`,`quantity`
    )
VALUES (1, 1,12),
(1,6,8),
(1,9,10),
(1,4,6), 
    (2, 2,2), 
    (2, 3,5),
    (2,7,4),
    (2,1,8),
    (3,1,9),
    (3,10,11),
    (3,6,9),
    (3,5,6), 
    (3, 4,14),
    (4, 5,7),
    (4,6,8),
    (4,10,12),
    (4,8,10),
    (4,4,8),
    (5,10,9),
    (5,1,10), 
    (5, 2,11),
    (5, 6,3);
   
   

   
    
    
    
 